### ISSUE TITLE
Confetti dispose error

### ISSUE THREAD

**Issue by guyluz11** [guyluz11/infinite_horizons#104]
After pressing the next button on "Efficient Creative Tips" console print error

```dart
======== Exception caught by widgets library =======================================================
The following assertion was thrown while finalizing the widget tree:
A ConfettiController was used after being disposed.

Once you have called dispose() on a ConfettiController, it can no longer be used.
When the exception was thrown, this was the stack: 
#0      ChangeNotifier.debugAssertNotDisposed.<anonymous closure> (package:flutter/src/foundation/change_notifier.dart:179:9)
#1      ChangeNotifier.debugAssertNotDisposed (package:flutter/src/foundation/change_notifier.dart:186:6)
#2      ChangeNotifier.dispose (package:flutter/src/foundation/change_notifier.dart:375:27)
#3      _TipsOrganismState.dispose (package:infinite_horizons/presentation/organisms/intro/tips_organism.dart:51:24)
#4      StatefulElement.unmount (package:flutter/src/widgets/framework.dart:5696:11)
#5      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2077:13)
#6      _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075:7)
#7      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5539:14)
#8      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073:13)
#9      _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075:7)
#10     MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6867:16)
#11     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073:13)
#12     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075:7)
#13     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6755:14)
#14     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073:13)
#15     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075:7)
#16     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5539:14)
#17     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073:13)
#18     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075:7)
#19     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5539:14)
#20     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073:13)
#21     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075:7)
#22     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6755:14)
#23     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073:13)
#24     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075:7)
#25     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5539:14)
#26     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073:13)
#27     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075:7)
#28     MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6867:16)
#29     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073:13)
#30     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075:7)
#31     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6755:14)
#32     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073:13)
#33     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075:7)
#34     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5539:14)
#35     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073:13)
#36     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075:7)
#37     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5539:14)
#38     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073:13)
#39     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075:7)
#40     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5539:14)
#41     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073:13)
#42     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075:7)
#43     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6755:14)
#44     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073:13)
#45     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075:7)
#46     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6755:14)
#47     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073:13)
#48     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075:7)
#49     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5539:14)
#50     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073:13)
#51     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075:7)
#52     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5539:14)
#53     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073:13)
#54     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075:7)
#55     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5539:14)
#56     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073:13)
#57     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075:7)
#58     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5539:14)
#59     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073:13)
#60     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075:7)
#61     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5539:14)
#62     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073:13)
#63     ListIterable.forEach (dart:_internal/iterable.dart:49:13)
#64     _InactiveElements._unmountAll (package:flutter/src/widgets/framework.dart:2086:25)
#65     BuildOwner.lockState (package:flutter/src/widgets/framework.dart:2765:15)
#66     BuildOwner.finalizeTree (package:flutter/src/widgets/framework.dart:3175:7)
#67     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:1143:19)
#68     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:443:5)
#69     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1392:15)
#70     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1313:9)
#71     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1171:5)
#72     _invoke (dart:ui/hooks.dart:312:13)
#73     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:419:5)
#74     _drawFrame (dart:ui/hooks.dart:283:31)
====================================================================================================
```

**Comment by M4dhav** [comment]
Done!
